// Generated by LiveScript 1.2.0
ctrl.simpletab = function($scope){
  $scope.tab = 1;
  return $scope.active = function(a, b){
    if (a === b) {
      return 'active';
    } else {
      return "";
    }
  };
};